config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies
  resources :lists
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }, allow_blank: false
  validates :movie_id , uniqueness: { scope: :list_id }
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, allow_blank: false
  validates :overview, presence: true, allow_blank: false
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
    @names = []
    @movies.each { |m|
    @names << m.title
  }
  @names_list = []
  @lists = List.all
  @lists.each { |l|
  @names_list << l.name
  }
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie_id = Movie.find_by(title: bookmark_params[:movie_id])
    @bookmark.list_id = List.find_by(name: bookmark_params[:list_id])
    @bookmark.save
    if @bookmark.save
    redirect_to lists_path
    else
      render 'new'
    end
  end


private

  def bookmark_params
  params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController


  def new
   @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def destroy
  end


private
  def list_params
  params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= form_for(@bookmark) do |f| %>
<%= f.label :comment %>
<%= f.text_field :comment %>
<%= f.label "choose your movie" %>
<%= f.select :movie_id, collection: @names%>
<%= f.label "choose your list" %>
<%= f.select :list_id, collection: @names_list%>
<%= f.submit%>
<% end %>

<%= console %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Movies Lists</h1>

<% @lists.each do |l|%>
<p><%= link_to l.name, list_path(l)%><p>
<% end %>

app/views/lists/new.html.erb
<%= form_for(@list) do |f| %>
<%= f.label :name%>
<%= f.text_field :name%>
<%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1>My <%= @list.name %> List</h1>

<h3>My movies</h3>

<% @movies.each do |l|%>
<p><%= l.title %><p>
<% end %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<div class="content-display-movies">
<% @movies.each do |e| %>
<div class="movie-content">
<div class="movie" style="background-image: url(<%=e.poster_url%>)" ></div>
<div class="text_content">
<p> <%= e.title %> </p>
<% number_of_stars = (e.rating.round(0))/2%>
<p><%="⭐️" * number_of_stars%></p>
<p> <%= e.overview %> </p>
</div>
</div>
<%end%>
</div>